/* -------------------------------------------------------------------------- */
/* (c) ali@balarabe.com                                      [libex_color_.h] */
/* -------------------------------------------------------------------------- */

#if !defined INCLUDED_LIBEX_COLOR__H
#define      INCLUDED_LIBEX_COLOR__H
#include "libex_color.h"

#define color_t                             lx_color_t
#define COLOR_NULL                          LX_COLOR_NULL

/* -------------------------------------------------------------------------- */

#define color_name_enum                     lx_color_name_enum

#define COLOR_ALICE_BLUE                    LX_COLOR_ALICE_BLUE
#define COLOR_ANTIQUE_WHITE                 LX_COLOR_ANTIQUE_WHITE
#define COLOR_AQUA                          LX_COLOR_AQUA
#define COLOR_AQUAMARINE                    LX_COLOR_AQUAMARINE
#define COLOR_AZURE                         LX_COLOR_AZURE
#define COLOR_BEIGE                         LX_COLOR_BEIGE
#define COLOR_BISQUE                        LX_COLOR_BISQUE
#define COLOR_BLACK                         LX_COLOR_BLACK
#define COLOR_BLANCHED_ALMOND               LX_COLOR_BLANCHED_ALMOND
#define COLOR_BLUE                          LX_COLOR_BLUE
#define COLOR_BLUE_VIOLET                   LX_COLOR_BLUE_VIOLET
#define COLOR_BROWN                         LX_COLOR_BROWN
#define COLOR_BURLY_WOOD                    LX_COLOR_BURLY_WOOD
#define COLOR_CADET_BLUE                    LX_COLOR_CADET_BLUE
#define COLOR_CHARTREUSE                    LX_COLOR_CHARTREUSE
#define COLOR_CHOCOLATE                     LX_COLOR_CHOCOLATE
#define COLOR_CORAL                         LX_COLOR_CORAL
#define COLOR_CORNFLOWER_BLUE               LX_COLOR_CORNFLOWER_BLUE
#define COLOR_CORNSILK                      LX_COLOR_CORNSILK
#define COLOR_CRIMSON                       LX_COLOR_CRIMSON
#define COLOR_CYAN                          LX_COLOR_CYAN
#define COLOR_DARK_BLUE                     LX_COLOR_DARK_BLUE
#define COLOR_DARK_CYAN                     LX_COLOR_DARK_CYAN
#define COLOR_DARK_GOLDEN_ROD               LX_COLOR_DARK_GOLDEN_ROD
#define COLOR_DARK_GRAY                     LX_COLOR_DARK_GRAY
#define COLOR_DARK_GREEN                    LX_COLOR_DARK_GREEN
#define COLOR_DARK_KHAKI                    LX_COLOR_DARK_KHAKI
#define COLOR_DARK_MAGENTA                  LX_COLOR_DARK_MAGENTA
#define COLOR_DARK_OLIVE_GREEN              LX_COLOR_DARK_OLIVE_GREEN
#define COLOR_DARK_ORANGE                   LX_COLOR_DARK_ORANGE
#define COLOR_DARK_ORCHID                   LX_COLOR_DARK_ORCHID
#define COLOR_DARK_RED                      LX_COLOR_DARK_RED
#define COLOR_DARK_SALMON                   LX_COLOR_DARK_SALMON
#define COLOR_DARK_SEA_GREEN                LX_COLOR_DARK_SEA_GREEN
#define COLOR_DARK_SLATE_BLUE               LX_COLOR_DARK_SLATE_BLUE
#define COLOR_DARK_SLATE_GRAY               LX_COLOR_DARK_SLATE_GRAY
#define COLOR_DARK_TURQUOISE                LX_COLOR_DARK_TURQUOISE
#define COLOR_DARK_VIOLET                   LX_COLOR_DARK_VIOLET
#define COLOR_DEEP_PINK                     LX_COLOR_DEEP_PINK
#define COLOR_DEEP_SKY_BLUE                 LX_COLOR_DEEP_SKY_BLUE
#define COLOR_DIM_GRAY                      LX_COLOR_DIM_GRAY
#define COLOR_DODGER_BLUE                   LX_COLOR_DODGER_BLUE
#define COLOR_FIRE_BRICK                    LX_COLOR_FIRE_BRICK
#define COLOR_FLORAL_WHITE                  LX_COLOR_FLORAL_WHITE
#define COLOR_FOREST_GREEN                  LX_COLOR_FOREST_GREEN
#define COLOR_FUCHSIA                       LX_COLOR_FUCHSIA
#define COLOR_GAINSBORO                     LX_COLOR_GAINSBORO
#define COLOR_GHOST_WHITE                   LX_COLOR_GHOST_WHITE
#define COLOR_GOLD                          LX_COLOR_GOLD
#define COLOR_GOLDEN_ROD                    LX_COLOR_GOLDEN_ROD
#define COLOR_GRAY                          LX_COLOR_GRAY
#define COLOR_GREEN                         LX_COLOR_GREEN
#define COLOR_GREEN_YELLOW                  LX_COLOR_GREEN_YELLOW
#define COLOR_HONEY_DEW                     LX_COLOR_HONEY_DEW
#define COLOR_HOT_PINK                      LX_COLOR_HOT_PINK
#define COLOR_INDIAN_RED                    LX_COLOR_INDIAN_RED
#define COLOR_INDIGO                        LX_COLOR_INDIGO
#define COLOR_IVORY                         LX_COLOR_IVORY
#define COLOR_KHAKI                         LX_COLOR_KHAKI
#define COLOR_LAVENDER                      LX_COLOR_LAVENDER
#define COLOR_LAVENDER_BLUSH                LX_COLOR_LAVENDER_BLUSH
#define COLOR_LAWN_GREEN                    LX_COLOR_LAWN_GREEN
#define COLOR_LEMON_CHIFFON                 LX_COLOR_LEMON_CHIFFON
#define COLOR_LIGHT_BLUE                    LX_COLOR_LIGHT_BLUE
#define COLOR_LIGHT_CORAL                   LX_COLOR_LIGHT_CORAL
#define COLOR_LIGHT_CYAN                    LX_COLOR_LIGHT_CYAN
#define COLOR_LIGHT_GOLDEN_ROD_YELLOW       LX_COLOR_LIGHT_GOLDEN_ROD_YELLOW
#define COLOR_LIGHT_GRAY                    LX_COLOR_LIGHT_GRAY
#define COLOR_LIGHT_GREEN                   LX_COLOR_LIGHT_GREEN
#define COLOR_LIGHT_PINK                    LX_COLOR_LIGHT_PINK
#define COLOR_LIGHT_SALMON                  LX_COLOR_LIGHT_SALMON
#define COLOR_LIGHT_SEA_GREEN               LX_COLOR_LIGHT_SEA_GREEN
#define COLOR_LIGHT_SKY_BLUE                LX_COLOR_LIGHT_SKY_BLUE
#define COLOR_LIGHT_SLATE_GRAY              LX_COLOR_LIGHT_SLATE_GRAY
#define COLOR_LIGHT_STEEL_BLUE              LX_COLOR_LIGHT_STEEL_BLUE
#define COLOR_LIGHT_YELLOW                  LX_COLOR_LIGHT_YELLOW
#define COLOR_LIME                          LX_COLOR_LIME
#define COLOR_LIME_GREEN                    LX_COLOR_LIME_GREEN
#define COLOR_LINEN                         LX_COLOR_LINEN
#define COLOR_MAGENTA                       LX_COLOR_MAGENTA
#define COLOR_MAROON                        LX_COLOR_MAROON
#define COLOR_MEDIUM_AQUAMARINE             LX_COLOR_MEDIUM_AQUAMARINE
#define COLOR_MEDIUM_BLUE                   LX_COLOR_MEDIUM_BLUE
#define COLOR_MEDIUM_ORCHID                 LX_COLOR_MEDIUM_ORCHID
#define COLOR_MEDIUM_PURPLE                 LX_COLOR_MEDIUM_PURPLE
#define COLOR_MEDIUM_SEA_GREEN              LX_COLOR_MEDIUM_SEA_GREEN
#define COLOR_MEDIUM_SLATE_BLUE             LX_COLOR_MEDIUM_SLATE_BLUE
#define COLOR_MEDIUM_SPRING_GREEN           LX_COLOR_MEDIUM_SPRING_GREEN
#define COLOR_MEDIUM_TURQUOISE              LX_COLOR_MEDIUM_TURQUOISE
#define COLOR_MEDIUM_VIOLET_RED             LX_COLOR_MEDIUM_VIOLET_RED
#define COLOR_MIDNIGHT_BLUE                 LX_COLOR_MIDNIGHT_BLUE
#define COLOR_MINT_CREAM                    LX_COLOR_MINT_CREAM
#define COLOR_MISTY_ROSE                    LX_COLOR_MISTY_ROSE
#define COLOR_MOCCASIN                      LX_COLOR_MOCCASIN
#define COLOR_NAVAJO_WHITE                  LX_COLOR_NAVAJO_WHITE
#define COLOR_NAVY                          LX_COLOR_NAVY
#define COLOR_NAVY_BLUE                     LX_COLOR_NAVY_BLUE
#define COLOR_OLD_LACE                      LX_COLOR_OLD_LACE
#define COLOR_OLIVE                         LX_COLOR_OLIVE
#define COLOR_OLIVE_DRAB                    LX_COLOR_OLIVE_DRAB
#define COLOR_ORANGE                        LX_COLOR_ORANGE
#define COLOR_ORANGE_RED                    LX_COLOR_ORANGE_RED
#define COLOR_ORCHID                        LX_COLOR_ORCHID
#define COLOR_PALE_GOLDEN_ROD               LX_COLOR_PALE_GOLDEN_ROD
#define COLOR_PALE_GREEN                    LX_COLOR_PALE_GREEN
#define COLOR_PALE_TURQUOISE                LX_COLOR_PALE_TURQUOISE
#define COLOR_PALE_VIOLET_RED               LX_COLOR_PALE_VIOLET_RED
#define COLOR_PAPAYA_WHIP                   LX_COLOR_PAPAYA_WHIP
#define COLOR_PEACH_PUFF                    LX_COLOR_PEACH_PUFF
#define COLOR_PERU                          LX_COLOR_PERU
#define COLOR_PINK                          LX_COLOR_PINK
#define COLOR_PLUM                          LX_COLOR_PLUM
#define COLOR_POWDER_BLUE                   LX_COLOR_POWDER_BLUE
#define COLOR_PURPLE                        LX_COLOR_PURPLE
#define COLOR_RED                           LX_COLOR_RED
#define COLOR_ROSY_BROWN                    LX_COLOR_ROSY_BROWN
#define COLOR_ROYAL_BLUE                    LX_COLOR_ROYAL_BLUE
#define COLOR_SADDLE_BROWN                  LX_COLOR_SADDLE_BROWN
#define COLOR_SALMON                        LX_COLOR_SALMON
#define COLOR_SANDY_BROWN                   LX_COLOR_SANDY_BROWN
#define COLOR_SEA_GREEN                     LX_COLOR_SEA_GREEN
#define COLOR_SEA_SHELL                     LX_COLOR_SEA_SHELL
#define COLOR_SIENNA                        LX_COLOR_SIENNA
#define COLOR_SILVER                        LX_COLOR_SILVER
#define COLOR_SKY_BLUE                      LX_COLOR_SKY_BLUE
#define COLOR_SLATE_BLUE                    LX_COLOR_SLATE_BLUE
#define COLOR_SLATE_GRAY                    LX_COLOR_SLATE_GRAY
#define COLOR_SNOW                          LX_COLOR_SNOW
#define COLOR_SPRING_GREEN                  LX_COLOR_SPRING_GREEN
#define COLOR_STEEL_BLUE                    LX_COLOR_STEEL_BLUE
#define COLOR_TAN                           LX_COLOR_TAN
#define COLOR_TEAL                          LX_COLOR_TEAL
#define COLOR_THISTLE                       LX_COLOR_THISTLE
#define COLOR_TOMATO                        LX_COLOR_TOMATO
#define COLOR_TURQUOISE                     LX_COLOR_TURQUOISE
#define COLOR_VIOLET                        LX_COLOR_VIOLET
#define COLOR_WHEAT                         LX_COLOR_WHEAT
#define COLOR_WHITE                         LX_COLOR_WHITE
#define COLOR_WHITE_SMOKE                   LX_COLOR_WHITE_SMOKE
#define COLOR_YELLOW                        LX_COLOR_YELLOW
#define COLOR_YELLOW_GREEN                  LX_COLOR_YELLOW_GREEN

#define COLOR_BLUE_1                        LX_COLOR_BLUE_1
#define COLOR_BLUE_2                        LX_COLOR_BLUE_2
#define COLOR_BLUE_3                        LX_COLOR_BLUE_3
#define COLOR_BLUE_4                        LX_COLOR_BLUE_4
#define COLOR_BLUE_5                        LX_COLOR_BLUE_5
#define COLOR_BLUE_6                        LX_COLOR_BLUE_6
#define COLOR_BLUE_7                        LX_COLOR_BLUE_7
#define COLOR_GRAY_1                        LX_COLOR_GRAY_1
#define COLOR_GRAY_2                        LX_COLOR_GRAY_2
#define COLOR_GRAY_3                        LX_COLOR_GRAY_3
#define COLOR_GRAY_4                        LX_COLOR_GRAY_4
#define COLOR_GRAY_5                        LX_COLOR_GRAY_5
#define COLOR_GRAY_6                        LX_COLOR_GRAY_6
#define COLOR_GRAY_7                        LX_COLOR_GRAY_7
#define COLOR_GREEN_1                       LX_COLOR_GREEN_1
#define COLOR_GREEN_2                       LX_COLOR_GREEN_2
#define COLOR_GREEN_3                       LX_COLOR_GREEN_3
#define COLOR_GREEN_4                       LX_COLOR_GREEN_4
#define COLOR_GREEN_5                       LX_COLOR_GREEN_5
#define COLOR_GREEN_6                       LX_COLOR_GREEN_6
#define COLOR_GREEN_7                       LX_COLOR_GREEN_7
#define COLOR_LIB_LIGHT_YELLOW              LX_COLOR_LIB_LIGHT_YELLOW

#define COLOR_ORANGE_100                    LX_COLOR_ORANGE_100
#define COLOR_ORANGE_110                    LX_COLOR_ORANGE_110
#define COLOR_ORANGE_120                    LX_COLOR_ORANGE_120
#define COLOR_ORANGE_130                    LX_COLOR_ORANGE_130
#define COLOR_ORANGE_140                    LX_COLOR_ORANGE_140
#define COLOR_ORANGE_150                    LX_COLOR_ORANGE_150
#define COLOR_ORANGE_160                    LX_COLOR_ORANGE_160
#define COLOR_ORANGE_170                    LX_COLOR_ORANGE_170
#define COLOR_ORANGE_180                    LX_COLOR_ORANGE_180
#define COLOR_ORANGE_190                    LX_COLOR_ORANGE_190
#define COLOR_ORANGE_200                    LX_COLOR_ORANGE_200
#define COLOR_ORANGE_210                    LX_COLOR_ORANGE_210
#define COLOR_ORANGE_220                    LX_COLOR_ORANGE_220
#define COLOR_ORANGE_70                     LX_COLOR_ORANGE_70
#define COLOR_ORANGE_80                     LX_COLOR_ORANGE_80
#define COLOR_ORANGE_90                     LX_COLOR_ORANGE_90
#define COLOR_RED_1                         LX_COLOR_RED_1
#define COLOR_RED_2                         LX_COLOR_RED_2
#define COLOR_RED_3                         LX_COLOR_RED_3
#define COLOR_RED_4                         LX_COLOR_RED_4
#define COLOR_RED_5                         LX_COLOR_RED_5
#define COLOR_RED_6                         LX_COLOR_RED_6
#define COLOR_RED_7                         LX_COLOR_RED_7

#define COLOR_SYS_3D_DK_SHADOW              LX_COLOR_SYS_3D_DK_SHADOW
#define COLOR_SYS_3D_FACE                   LX_COLOR_SYS_3D_FACE
#define COLOR_SYS_3D_HLIGHT                 LX_COLOR_SYS_3D_HLIGHT
#define COLOR_SYS_3D_LIGHT                  LX_COLOR_SYS_3D_LIGHT
#define COLOR_SYS_3D_SHADOW                 LX_COLOR_SYS_3D_SHADOW
#define COLOR_SYS_ACTIVE_BORDER             LX_COLOR_SYS_ACTIVE_BORDER
#define COLOR_SYS_ACTIVE_TITLE_BAR          LX_COLOR_SYS_ACTIVE_TITLE_BAR
#define COLOR_SYS_ACTIVE_TITLE_BAR_TEXT     LX_COLOR_SYS_ACTIVE_TITLE_BAR_TEXT
#define COLOR_SYS_APP_WORKSPACE             LX_COLOR_SYS_APP_WORKSPACE
#define COLOR_SYS_BTN_FACE                  LX_COLOR_SYS_BTN_FACE
#define COLOR_SYS_BTN_SHADOW                LX_COLOR_SYS_BTN_SHADOW
#define COLOR_SYS_BTN_TEXT                  LX_COLOR_SYS_BTN_TEXT
#define COLOR_SYS_DESKTOP                   LX_COLOR_SYS_DESKTOP
#define COLOR_SYS_GRAY_TEXT                 LX_COLOR_SYS_GRAY_TEXT
#define COLOR_SYS_HLIGHT                    LX_COLOR_SYS_HLIGHT
#define COLOR_SYS_HLIGHT_TEXT               LX_COLOR_SYS_HLIGHT_TEXT
#define COLOR_SYS_INACTIVE_BORDER           LX_COLOR_SYS_INACTIVE_BORDER
#define COLOR_SYS_INACTIVE_CAPTION_TEXT     LX_COLOR_SYS_INACTIVE_CAPTION_TEXT
#define COLOR_SYS_INACTIVE_TITLE_BAR        LX_COLOR_SYS_INACTIVE_TITLE_BAR
#define COLOR_SYS_INACTIVE_TITLE_BAR_TEXT   LX_COLOR_SYS_INACTIVE_TITLE_BAR_TEXT
#define COLOR_SYS_INFO_BACK                 LX_COLOR_SYS_INFO_BACK
#define COLOR_SYS_INFO_TEXT                 LX_COLOR_SYS_INFO_TEXT
#define COLOR_SYS_MENU_BAR                  LX_COLOR_SYS_MENU_BAR
#define COLOR_SYS_MENU_TEXT                 LX_COLOR_SYS_MENU_TEXT
#define COLOR_SYS_SCROLLBARS                LX_COLOR_SYS_SCROLLBARS
#define COLOR_SYS_TITLE_BAR_TEXT            LX_COLOR_SYS_TITLE_BAR_TEXT
#define COLOR_SYS_WND_BACK                  LX_COLOR_SYS_WND_BACK
#define COLOR_SYS_WND_FRAME                 LX_COLOR_SYS_WND_FRAME
#define COLOR_SYS_WND_TEXT                  LX_COLOR_SYS_WND_TEXT

/* -------------------------------------------------------------------------- */
/* Constructors:                                                              */

#define Color_fromName                      lx_Color_fromName
#define Color_fromSystem                    lx_Color_fromSystem
#define Color_fromRgb                       lx_Color_fromRgb
#define Color_fromValue                     lx_Color_fromValue

/* -------------------------------------------------------------------------- */
/* Methods:                                                                   */

#define Color_getBlue                       lx_Color_getBlue
#define Color_getGreen                      lx_Color_getGreen
#define Color_getRed                        lx_Color_getRed
#define Color_brighten                      lx_Color_brighten
#define Color_shift                         lx_Color_shift
#define Color_blend                         lx_Color_blend
#define Color_rgb                           lx_Color_rgb

#endif                                                                   /*eof*/
